### ISSUE TITLE
61. Please log in the specific user with their credentials.

### ISSUE THREAD

**Issue by januo-io** [januo-org/proof-of-concepts#119]

**Comment by fourtimes** [comment]
_**login the user via the below link**_
https://972549640330.signin.aws.amazon.com/console
```sh
    # user
   admin-user

   #password
   Password@12
```

![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/044019bf-fdfd-4ebe-9a9f-ca73b8da99d6)


**_once enter into the `admin-user` we have to change the password instead of old password_**
![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/c7248c0b-3fff-42e9-a6c7-25690ad35b4d)


**_Finally, login to the `admin-user`_**
![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/c6831e83-aa78-4ce3-bdbb-0f73e4f9b461)
