### ISSUE TITLE
how can we create the NAT gateway?

### ISSUE THREAD

**Issue by fourtimes** [januo-org/proof-of-concepts#39]

**Comment by dodonotdo** [comment]
**Network Address Translation(NAT):**
A NAT gateway is a Network Address Translation (NAT) service. You can use a NAT gateway so that instances in a private subnet can connect to services outside your VPC but external services cannot initiate a connection with those instances.

1. Create the NAT Gateway
![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/8642ee67-e506-4014-8b89-21f583916d40)

![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/da075ee7-4522-4956-9a5a-6d1d35219a13)

2. After creating the NAT gateway, we need to route the traffic to the private rt. so that we can communicate through the internet.

![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/ffc6774e-cef7-4d6a-8e73-a7affd627436)

**Checking Purpose:**
1. We have to login the public instance through SSH.
2.  Inside the public instance we have to login the private instance through SSH.
3.  After logging in, we check whether the internet process is working or not. While working, we need to put in some commands. In case it is not working, we need to check the creation of the Nat Gateway.
       `sudo apt install  vim`

**Comment by fourtimes** [comment]
@dodonotdo awesome
