### ISSUE TITLE
7. Create a disk from exising snapshot and attach it on the ubuntu machine. Make sure the existing data is available or not.

### ISSUE THREAD

**Issue by januo-io** [januo-org/proof-of-concepts#56]

**Comment by januo-io** [comment]
@fourtimes  This is in connection with.  https://github.com/januo-org/proof-of-concepts/issues/50

**Comment by fourtimes** [comment]
1. create the volume using exisiting snapshot.
2. attach the volume into the ubuntu machine
3. then mount the disk in that ubunut machine
```bash
sudo file -s /dev/xvdf
sudo mkdir -p /newvolume
cd /
sudo mount /dev/xvdf /newvolume
```
![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/bca80033-97a9-4164-ab32-0d4a2ff66975)

**Comment by januo-io** [comment]
Could you show me the output  `cat /etc/fstab`

**Comment by januo-io** [comment]
@fourtimes @rio-ke Ensure that both individuals are familiar with the process.

**Comment by fourtimes** [comment]
1. Open the AWS Management Console and navigate to the EC2 service.
2. Launch an Ubuntu EC2 instance.
3. Create the snapshot using existing Ubuntu machine disk.

Workflow
------------

- [ ] Open the AWS Management Console and navigate to the EC2 service.
- [ ] Launch an Ubuntu EC2 instance.
- [ ] Locate the snapshot you want to use.
- [ ] Click on "Snapshots" in the left-hand navigation pane and find the snapshot with corresponding ID. select the snapshot and click `"Actions"` > `"create volume from snapshot"`
- [ ] In the `"create volume"` dialog box specify the desired size and availability zone for the new volume. Make sure to choose an availability zone that matches your EC2 instance.
- [ ] Click `"Create"` to create the volume from the snapshot.
- [ ] Stop your Ubuntu EC2 instance.
- [ ] After the instance is stopped, select it and click `"Actions"` > `"Attach Volume".` For the device name, use something like "/dev/xvdf" or choose an available device name.
- [ ] Click `"Attach"`
- [ ]  to attach the volume to your instance.
- [ ] Start the instance
- [ ] Once the instance is running, SSH into your Ubuntu machine.
- [ ] Run the following command to check if the newly attached volume is available: This command will display the available block devices and their mount points. You should see the newly attached volume listed.
```ah
sudo lsblk
df -Th
```
- [ ] If the volume is not automatically mounted, you can mount it manually. Create a mount point directory using the following command:
```sh
sudo mkdir /mnt/new_volume
```
- [ ] Mount the volume to the newly created directory: Replace "/dev/xvdf" with the appropriate device name assigned to the new volume.
```sh
sudo mount /dev/xvdf /mnt/new_volume

# note:
# Replace "/dev/xvdf" with the appropriate device name assigned to the new volume.
```
- [ ] Verify that the data is available by checking the contents of the mounted directory:
```sh
ls /mnt/new_volume
df -Th
sudo lsblk
```
In case if you are umount the disk please following the below steps;
----------------------------------------------------------------------------------------
```sh
sudo umount /mnt/new_volume
```

mount

**Comment by januo-io** [comment]
@fourtimes Have you made this entry into the fatab file?

**Comment by fourtimes** [comment]
Automatically mount an attached volume after reboot (fstab) file
----------------------------------------------------------------------------------
- After the disk is mounted we have to follow the following steps. Because if we suddenly reboot the instance. The mounted disk will not be in the mounted list. so, we have to automatically mount an attached volume after reboot the instance. so that we can follow this method.
```sh
sudo cp /etc/fstab /etc/fstab.orig
sudo blkid
sudo lsblk -o +UUID
```
```sh
sudo vim /etc/fstab

# paste the below details for fstab file
UUID=aebf131c-6957-451e-8d34-ec978d9581ae  /data  xfs  defaults,nofail  0  2

note:
------
1. The UUID must be taken from the particular mounted disk.
2. /data means specified mounted disk. choose our mounted disk depends upon our situation.
```
Reference - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

Example 1
--------------
### Mounted disk `with` Automatically mount an attached volume after reboot.
**Original mount**
![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/23488275-89b1-4c20-b2d3-55a238b2c60a)
**After reboot  the instance we will get a same mount directory**
![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/6b502130-1c4d-48d2-85b0-f6b4dd647afa)

Example 2
--------------
### Mounted disk `without` Automatically mount an attached volume after reboot.
**Original mount**
![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/a707e670-4ace-419f-8864-ea13b1dbfef4)

![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/f7967d0d-0b81-4154-858e-51f97146728a)

**After reboot  the instance we will not get a same mount directory**
![image](https://github.com/januo-org/proof-of-concepts/assets/91359308/c2f109c0-0cb8-466d-bb33-0e3d98460368)
